const PDFDocument = require('pdfkit');
const fs = require('fs');

const doc = new PDFDocument({ margin: 50 });
doc.pipe(fs.createWriteStream('C:\\Users\\Dell\\Documents\\project3\\synapseiq-ai\\sample-report.pdf'));

doc.fontSize(24).font('Helvetica-Bold').text('SynapseIQ AI - Sample Report', { align: 'center' });
doc.moveDown(0.5);
doc.fontSize(12).font('Helvetica').fillColor('#666').text('Quarterly Business Performance Analysis - Q4 2024', { align: 'center' });
doc.moveDown(1);

doc.fontSize(16).font('Helvetica-Bold').fillColor('#000').text('Executive Summary');
doc.moveDown(0.3);
doc.fontSize(11).font('Helvetica').fillColor('#333');
doc.text('This report provides a comprehensive analysis of Q4 2024 business performance across all departments. Key metrics show a 15% increase in overall revenue compared to Q3, with Sales and Marketing departments leading the growth trajectory.');
doc.moveDown(1);

doc.fontSize(16).font('Helvetica-Bold').fillColor('#000').text('Revenue Overview');
doc.moveDown(0.3);
doc.fontSize(11).font('Helvetica').fillColor('#333');

const revenues = [
  ['Department', 'Q3 Revenue', 'Q4 Revenue', 'Growth'],
  ['Sales', '$1,250,000', '$1,480,000', '+18.4%'],
  ['Marketing', '$890,000', '$1,020,000', '+14.6%'],
  ['Engineering', '$2,100,000', '$2,350,000', '+11.9%'],
  ['HR', '$320,000', '$345,000', '+7.8%'],
  ['Total', '$4,560,000', '$5,195,000', '+13.9%'],
];

let y = doc.y;
revenues.forEach((row, i) => {
  const x = 50;
  const colWidths = [120, 110, 110, 80];
  row.forEach((cell, j) => {
    const font = i === 0 || i === revenues.length - 1 ? 'Helvetica-Bold' : 'Helvetica';
    doc.font(font).fontSize(10).fillColor(i === 0 ? '#000' : '#333');
    doc.text(cell, x + colWidths.slice(0, j).reduce((a, b) => a + b, 0), y, { width: colWidths[j], align: j > 0 ? 'right' : 'left' });
  });
  y += 20;
  if (i === 0) {
    doc.moveTo(50, y - 3).lineTo(470, y - 3).stroke('#ccc');
  }
});
doc.moveDown(1.5);

doc.fontSize(16).font('Helvetica-Bold').fillColor('#000').text('Top Performing Employees');
doc.moveDown(0.3);
doc.fontSize(11).font('Helvetica').fillColor('#333');

const employees = [
  { name: 'Omar Farooq', dept: 'Engineering', rating: 4.9, projects: 18 },
  { name: 'Amna Raza', dept: 'Engineering', rating: 4.7, projects: 16 },
  { name: 'Mehwish Bano', dept: 'Marketing', rating: 4.7, projects: 11 },
  { name: 'Usman Riaz', dept: 'Engineering', rating: 4.8, projects: 15 },
  { name: 'Zainab Malik', dept: 'Marketing', rating: 4.6, projects: 9 },
];

employees.forEach((emp, i) => {
  doc.text(`${i + 1}. ${emp.name} (${emp.dept}) - Rating: ${emp.rating}/5.0 | Projects: ${emp.projects}`);
});
doc.moveDown(1);

doc.fontSize(16).font('Helvetica-Bold').fillColor('#000').text('Key Insights');
doc.moveDown(0.3);
doc.fontSize(11).font('Helvetica').fillColor('#333');

const insights = [
  'Engineering department has the highest average salary at $98,500',
  'Sales department generates the highest revenue per employee',
  'Employee retention rate is 92% - above industry average of 85%',
  'Average employee rating across all departments: 4.2/5.0',
  'Marketing ROI increased by 22% compared to previous quarter',
  'Lahore office has the most employees (11), followed by Karachi (9)',
];

insights.forEach(insight => {
  doc.text(`• ${insight}`);
});
doc.moveDown(1);

doc.fontSize(16).font('Helvetica-Bold').fillColor('#000').text('Recommendations');
doc.moveDown(0.3);
doc.fontSize(11).font('Helvetica').fillColor('#333');

const recommendations = [
  'Increase hiring in Sales department to capitalize on growth momentum',
  'Implement performance bonus system for employees rated above 4.5',
  'Expand Marketing budget by 15% based on improved ROI metrics',
  'Consider opening new office in Faisalabad to expand regional presence',
  'Launch employee training program to improve average rating to 4.5+',
];

recommendations.forEach(rec => {
  doc.text(`→ ${rec}`);
});
doc.moveDown(2);

doc.fontSize(10).font('Helvetica').fillColor('#999').text('Generated by SynapseIQ AI Analytics Engine', { align: 'center' });
doc.text('Report Date: December 2024', { align: 'center' });

doc.end();
console.log('PDF created: sample-report.pdf');
